version: '3'

networks:
    backend:
        driver: bridge

volumes:
    mysql:
        driver: local
    phpmyadmin:
        driver: local
    redis:
        driver: local
    memcached:
        driver: local

services:
    # Application
    application:
        build:
            context: .docker/application
            args:
                - UBUNTU_SOURCE=${UBUNTU_SOURCE}
                - PHP_VERSION=${PHP_VERSION}
                - INSTALL_PHPREDIS=true
                - INSTALL_NODE=true
                - INSTALL_YARN=true
                - http_proxy
                - https_proxy
                - no_proxy
        volumes:
            - ./:/var/www/laravel-examine:cached
            - .docker/php-worker/supervisord.d:/etc/supervisord.d
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        tty: true
        networks:
            - backend
        links:
            - docker-in-docker

    # php-fpm
    php-fpm:
        build:
            context: .docker/php-fpm
            args:
                - PHP_VERSION=${PHP_VERSION}
        image: marimasak-app
        depends_on:
            - mysql
            - redis
        networks:
            - backend
        volumes:
            - ./:/var/www/laravel-examine:cached
        links:
            - docker-in-docker

    # PHP Worker
    php-worker:
        build:
            context: .docker/php-worker
            args:
                - PHP_VERSION=${PHP_VERSION}
        restart: unless-stopped
        volumes:
            - ./:/application:cached
            - .docker/php-worker/supervisord.d:/etc/supervisord.d
        depends_on:
            - php-fpm
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            - backend

    # Nginx Server
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            - ./:/var/www/laravel-examine:cached
            - .docker/logs/nginx/:/var/log/nginx
            - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - .docker/nginx/ssl/:/etc/nginx/ssl
        ports:
            - "80:80"
        depends_on:
            - php-fpm
        networks:
            - backend

    # MySQL
    mysql:
        image: mysql:8
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - .docker/data/mysql:/var/lib/mysql
            - .docker/logs/mysql:/var/log/mysql
        ports:
            - "3306:3306"
        networks:
            - backend

    # Redis
    redis:
        build:
            context: .docker/redis
            args:
                - REDIS_PORT=${REDIS_PORT}
        restart: unless-stopped
        volumes:
            - .docker/data/redis:/data
            - .docker/logs/redis:/var/log/redis
        environment:
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        networks:
            - backend

    # PhpMyAdmin
    phpmyadmin:
        build: .docker/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: ${DB_HOST}
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - backend

    # Docker-In-Docker
    docker-in-docker:
        image: docker:19.03-dind
        environment:
            DOCKER_TLS_SAN: DNS:docker-in-docker
        privileged: true
        volumes:
            - ./:/var/www/laravel-examine:cached
            - .docker/docker-in-docker:/certs/client
        expose:
            - 2375
        networks:
            - backend
